services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # command: ["npm", "start"]
